Fix analytics cookie consent
option26/quarantine-hero pull request #359
Opened 2020-09-27 19:03 UTC by jagaSto

**What changes does this PR introduce**

Analytics are currently not working, because we missed adding functionality to enable them when we refactored the cookie consent. This is fixed now fixed by initializing them once the cookie consent is given (with `setAnalytics`)

2020-09-27 19:16 UTC, florianschmidt1994 approved these changes
Looks fine to me

2020-09-29 08:20 UTC, mauriceackel approved these changes

2020-09-29 08:22 UTC, mauriceackel requested changes
Please check the listing error

2020-09-29 15:53 UTC, mauriceackel approved these changes

2020-09-29 15:53 UTC, merged