feat: add max amount of open requests per user
option26/quarantine-hero pull request #392
Opened 2021-03-10 20:57 UTC by jagaSto

**What changes does this PR introduce**

* adds a feature to limit the number of open requests a user can have to avoid potential spam.
* in this case, we show a short hint explaining to the user that they should close one of their open entries first.
* hotline account can always create new posts

## Preview

![Screenshot 2021-03-10 at 21 33 26](https://user-images.githubusercontent.com/20641332/110696612-93172f80-81eb-11eb-8627-71deaef90349.png)

2021-03-11 09:33 UTC, mauriceackel requested changes

2021-03-11 09:33 UTC, mauriceackel commented on src/views/AskForHelp.jsx
>    const isHotline = user && user.uid === hotlineId;
```suggestion
  const isHotline = useMemo(() => user && user.uid === hotlineId, [user, hotlineId]);
```

If we include this constant in the dependency array below, we should memorize it, otherwise the useMemo hook below will be recomputed unnecessarily

2021-03-11 09:33 UTC, mauriceackel commented on src/views/AskForHelp.jsx
> +  const showAllowedRequestsHint = useMemo(() => !isHotline || (existingDocsForUser && existingDocsForUser.length > allowedOpenRequestsPerUser), [existingDocsForUser]);
```suggestion
  const showAllowedRequestsHint = useMemo(() => !isHotline || (existingDocsForUser && existingDocsForUser.length > allowedOpenRequestsPerUser), [existingDocsForUser, isHotline]);
```

We have to add `isHotline` in the dependency array here.

2021-03-11 09:33 UTC, mauriceackel commented on src/views/AskForHelp.jsx
> +  const showAllowedRequestsHint = useMemo(() => !isHotline || (existingDocsForUser && existingDocsForUser.length > allowedOpenRequestsPerUser), [existingDocsForUser]);
Wouldn't we need to test for `existingDocsForUser.length >= allowedOpenRequestsPerUser`, otherwise we would allow 4 instead of 3 requests?

2021-03-11 18:04 UTC, jagaSto commented on src/views/AskForHelp.jsx
> +  const showAllowedRequestsHint = useMemo(() => !isHotline || (existingDocsForUser && existingDocsForUser.length > allowedOpenRequestsPerUser), [existingDocsForUser]);
yeah lol 😄

2021-03-22 20:23 UTC, mauriceackel approved these changes

2021-03-23 12:02 UTC, merged